apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: ctse-micro
  name: ctse-micro
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ctse-micro
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ctse-micro
    spec:
      containers:
      - image: navodyapasqual25/ctse-microservice:{{tag}}
        imagePullPolicy: Always
        name: ctse-microservice
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 8081
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30