apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse-micro
  name: ctse-micro
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: ctse-micro
status:
  loadBalancer: {}
  